version: "3.3"
services:
  mongodb:
    image: mongo:7.0
    container_name: my_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: antoine
    volumes:
      - ./sample_training:/data/db
      - /home/antoine/spotify/data/mongodb_data:/data/db_local
    ports:
      - 27017:27017
